spring.application.name=mylibrary
spring.profiles.active=test

spring.data.mongodb.uri=mongodb://localhost:27017/mylibrary

jwt.secret=Q9xT7vL2mN8rF4yH6uJ0pW3aZ5cE1kR8dS2bV6tY9gM4hC7q
jwt.expiration=3600000

