spring.application.name=mylibrary
spring.profiles.active=test

spring.data.mongodb.uri=mongodb://localhost:27017/mylibrary

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
security.jwt.duration=${JWT_DURATION:6000000}
cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200}
